services:
  api:
    build:
      context: .
    image: patient:latest
    ports:
      - 5000:8080
    environment:
      - ConnectionStrings__DefaultConnection=Host=database;User ID=postgres;Password=secret;Database=postgres;
    depends_on:
      - database

  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DATABASE=postgres
    volumes:
      - patients_volume:/var/lib/postgresql/pgdata

volumes:
  patients_volume: